// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/COMMultReg.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// d_cmb_rcpp
double d_cmb_rcpp(unsigned int x, unsigned int m, double p, double nu, bool log, bool normalize);
RcppExport SEXP _COMMultReg_d_cmb_rcpp(SEXP xSEXP, SEXP mSEXP, SEXP pSEXP, SEXP nuSEXP, SEXP logSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(d_cmb_rcpp(x, m, p, nu, log, normalize));
    return rcpp_result_gen;
END_RCPP
}
// r_cmb_rcpp
arma::vec r_cmb_rcpp(unsigned int n, unsigned int m, double p, double nu);
RcppExport SEXP _COMMultReg_r_cmb_rcpp(SEXP nSEXP, SEXP mSEXP, SEXP pSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(r_cmb_rcpp(n, m, p, nu));
    return rcpp_result_gen;
END_RCPP
}
// p_cmb_rcpp
double p_cmb_rcpp(unsigned int x, unsigned int m, double p, double nu);
RcppExport SEXP _COMMultReg_p_cmb_rcpp(SEXP xSEXP, SEXP mSEXP, SEXP pSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(p_cmb_rcpp(x, m, p, nu));
    return rcpp_result_gen;
END_RCPP
}
// q_cmb_rcpp
double q_cmb_rcpp(unsigned int q, unsigned int m, double p, double nu);
RcppExport SEXP _COMMultReg_q_cmb_rcpp(SEXP qSEXP, SEXP mSEXP, SEXP pSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type q(qSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(q_cmb_rcpp(q, m, p, nu));
    return rcpp_result_gen;
END_RCPP
}
// normconst_cmb_rcpp
double normconst_cmb_rcpp(unsigned int m, double p, double nu, bool log);
RcppExport SEXP _COMMultReg_normconst_cmb_rcpp(SEXP mSEXP, SEXP pSEXP, SEXP nuSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(normconst_cmb_rcpp(m, p, nu, log));
    return rcpp_result_gen;
END_RCPP
}
// d_cmb_sample_rcpp
arma::vec d_cmb_sample_rcpp(const arma::vec& x, const arma::vec& m, const arma::vec& p, const arma::vec& nu, bool log);
RcppExport SEXP _COMMultReg_d_cmb_sample_rcpp(SEXP xSEXP, SEXP mSEXP, SEXP pSEXP, SEXP nuSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(d_cmb_sample_rcpp(x, m, p, nu, log));
    return rcpp_result_gen;
END_RCPP
}
// gunterize
Rcpp::List gunterize(const arma::umat& X, bool all);
RcppExport SEXP _COMMultReg_gunterize(SEXP XSEXP, SEXP allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type all(allSEXP);
    rcpp_result_gen = Rcpp::wrap(gunterize(X, all));
    return rcpp_result_gen;
END_RCPP
}
// loglik_score_fim_cmm
Rcpp::List loglik_score_fim_cmm(const Rcpp::List& par, const Rcpp::List& dat_xform, unsigned int baseline);
RcppExport SEXP _COMMultReg_loglik_score_fim_cmm(SEXP parSEXP, SEXP dat_xformSEXP, SEXP baselineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dat_xform(dat_xformSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type baseline(baselineSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_score_fim_cmm(par, dat_xform, baseline));
    return rcpp_result_gen;
END_RCPP
}
// r_cmm_internal_rcpp
arma::mat r_cmm_internal_rcpp(unsigned int n, unsigned int m, const arma::vec& p, double nu, unsigned int burn, unsigned int thin, const arma::vec& x_init, unsigned int report);
RcppExport SEXP _COMMultReg_r_cmm_internal_rcpp(SEXP nSEXP, SEXP mSEXP, SEXP pSEXP, SEXP nuSEXP, SEXP burnSEXP, SEXP thinSEXP, SEXP x_initSEXP, SEXP reportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x_init(x_initSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type report(reportSEXP);
    rcpp_result_gen = Rcpp::wrap(r_cmm_internal_rcpp(n, m, p, nu, burn, thin, x_init, report));
    return rcpp_result_gen;
END_RCPP
}
// d_cmm_rcpp
double d_cmm_rcpp(const arma::vec& x, const arma::vec& p, double nu, bool log, bool normalize);
RcppExport SEXP _COMMultReg_d_cmm_rcpp(SEXP xSEXP, SEXP pSEXP, SEXP nuSEXP, SEXP logSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(d_cmm_rcpp(x, p, nu, log, normalize));
    return rcpp_result_gen;
END_RCPP
}
// normconst_cmm_rcpp
double normconst_cmm_rcpp(unsigned int m, const arma::vec& p, double nu, bool log);
RcppExport SEXP _COMMultReg_normconst_cmm_rcpp(SEXP mSEXP, SEXP pSEXP, SEXP nuSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(normconst_cmm_rcpp(m, p, nu, log));
    return rcpp_result_gen;
END_RCPP
}
// d_cmm_sample_rcpp
arma::vec d_cmm_sample_rcpp(const arma::mat& X, const arma::mat& P, const arma::vec& nu, bool log, bool normalize);
RcppExport SEXP _COMMultReg_d_cmm_sample_rcpp(SEXP XSEXP, SEXP PSEXP, SEXP nuSEXP, SEXP logSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(d_cmm_sample_rcpp(X, P, nu, log, normalize));
    return rcpp_result_gen;
END_RCPP
}
// pinv
arma::mat pinv(const arma::mat& x);
RcppExport SEXP _COMMultReg_pinv(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pinv(x));
    return rcpp_result_gen;
END_RCPP
}
// lchoose
double lchoose(const arma::vec& x);
RcppExport SEXP _COMMultReg_lchoose(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(lchoose(x));
    return rcpp_result_gen;
END_RCPP
}
// normalize
arma::vec normalize(const arma::vec& x, bool na_rm);
RcppExport SEXP _COMMultReg_normalize(SEXP xSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize(x, na_rm));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_COMMultReg_d_cmb_rcpp", (DL_FUNC) &_COMMultReg_d_cmb_rcpp, 6},
    {"_COMMultReg_r_cmb_rcpp", (DL_FUNC) &_COMMultReg_r_cmb_rcpp, 4},
    {"_COMMultReg_p_cmb_rcpp", (DL_FUNC) &_COMMultReg_p_cmb_rcpp, 4},
    {"_COMMultReg_q_cmb_rcpp", (DL_FUNC) &_COMMultReg_q_cmb_rcpp, 4},
    {"_COMMultReg_normconst_cmb_rcpp", (DL_FUNC) &_COMMultReg_normconst_cmb_rcpp, 4},
    {"_COMMultReg_d_cmb_sample_rcpp", (DL_FUNC) &_COMMultReg_d_cmb_sample_rcpp, 5},
    {"_COMMultReg_gunterize", (DL_FUNC) &_COMMultReg_gunterize, 2},
    {"_COMMultReg_loglik_score_fim_cmm", (DL_FUNC) &_COMMultReg_loglik_score_fim_cmm, 3},
    {"_COMMultReg_r_cmm_internal_rcpp", (DL_FUNC) &_COMMultReg_r_cmm_internal_rcpp, 8},
    {"_COMMultReg_d_cmm_rcpp", (DL_FUNC) &_COMMultReg_d_cmm_rcpp, 5},
    {"_COMMultReg_normconst_cmm_rcpp", (DL_FUNC) &_COMMultReg_normconst_cmm_rcpp, 4},
    {"_COMMultReg_d_cmm_sample_rcpp", (DL_FUNC) &_COMMultReg_d_cmm_sample_rcpp, 5},
    {"_COMMultReg_pinv", (DL_FUNC) &_COMMultReg_pinv, 1},
    {"_COMMultReg_lchoose", (DL_FUNC) &_COMMultReg_lchoose, 1},
    {"_COMMultReg_normalize", (DL_FUNC) &_COMMultReg_normalize, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_COMMultReg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
